Updated to support Vapor 3
vapor-community/wkhtmltopdf pull request #5
Opened 2019-05-08 10:47 UTC by kimdv

2019-05-08 10:49 UTC, kimdv commented
@bygri would you mind review this?

2019-05-08 22:41 UTC, bygri commented
Hi Kim, thanks for taking a stab at this! The essential challenge in moving from Vapor 2 to Vapor 3 is that calling out to `wkhtmltopdf` is a blocking operation, and we must be careful not to block the event loop. `generatePDF()` must return a `Future<Data>` - I'd suggest using NIO's `BlockingIOThreadPool`.

2019-05-09 06:07 UTC, kimdv commented
Thanks for the fast feedback @bygri !

I have tried what you suggested, hope it is in the right direction! 🚀

2019-05-09 08:24 UTC, kimdv commented on Sources/wkhtmltopdf/Document+Generate.swift
> +    public func generatePDF(on req: Request) throws -> Future<Data> {
It is possible to change to `public func generatePDF(on worker: Container) throws -> Future<Data>`

This was we can only depend on the `vapor/service`

2019-05-09 23:38 UTC, bygri requested changes
Much better. I have a couple of further comments, plus update the Readme, and then I think it's good to go.

2019-05-09 23:38 UTC, bygri commented on Package.resolved
> +{
This file and `Package.pins` should be removed.

2019-05-09 23:38 UTC, bygri commented on Package.swift
> +        // Products define the executables and libraries produced by a package, and make them visible to other packages.
I think these boilerplate comments can safely be removed.

2019-05-09 23:38 UTC, bygri commented on Sources/wkhtmltopdf/Document+Generate.swift
>  #if os(Linux) && !swift(>=3.1)
Since we are now targeting Swift 4.2, there is no need for this conditional typealias any more.

2019-05-09 23:38 UTC, bygri commented on Sources/wkhtmltopdf/Document+Generate.swift
> +                try File(data: page.content, filename: filename).data.write(to: URL(fileURLWithPath: filename))
Why not just use `try page.content.write(to:  URL(fileURLWithPath: filename))` here?

2019-05-09 23:38 UTC, bygri commented on Sources/wkhtmltopdf/Document.swift
> +    static var zoom: String = "1.3"
I _think_ static vars are no longer a good idea with Vapor 3. I think it's reasonable to either make it a simple var which the user sets on each Document, or to make it an argument to `generatePDF()`.

2019-05-10 05:50 UTC, kimdv commented on README.md
> +.package(url: "https://github.com/vapor-community/wkhtmltopdf.git", from: "2.0.0"),
@bygri I have added this, and assumed next release will be 2.0.0 😅

2019-05-13 02:19 UTC, merged